---
name: Build, Publish, and Attest

permissions:
  contents: read

on:
  pull_request:

  release:
    types:
      - published

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@5f637c833aa76bc99372a1dc9a6f8bcd8056fb85 # v1.12.0

    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    with:
      file: Containerfile
      output: image
      push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}

    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
